name: Corretto CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build_corretto_8:
    name: Build on Corretto 8
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        java: ['8', '11']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-micronaut-core-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-gradle-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-micronaut-core-wrapper-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-micronaut-core-wrapper-
    - uses: alvarosanchez/corretto-amazon-linux-action@master
      with:
        corretto-version: ${{ matrix.java }}
    - run: java -version
    - uses: docker://amazoncorretto:8
    - run: java -version
    - name: Build with Gradle
#      run: ./gradlew check --no-daemon --parallel --continue
      run: ./gradlew --version